### ISSUE TITLE
K8s imposes restrictions on job names

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#1488] opened 2019-10-18 17:58 UTC
Tried to run a job with the name: `KS count unique test` and received the following error.

```
Error: Service \"ts-exc-KS-count-unique-test-c500cfb5-b82f\" is invalid: metadata.name: Invalid value: \"ts-exc-KS-count-unique-test-c500cfb5-b82f\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')\n
```

This implies we either need restrictions on what can be in a job name to conform to K8s rules or the normalization for the K8s label generation needs to do more.

**Comment by godber** [comment] 2019-10-18 21:29
Huh, looks like you're the first person to try and use caps.

We already normalize so we'll add this to the set of things we do.  Thanks

**Comment by godber** [comment] 2020-01-13 23:51
Confirmed this, will be fixed in https://github.com/terascope/teraslice/pull/1615

Now this job:

```
{
    "name": "example-data-BAD-generator-job",
    "lifecycle": "once",
    "workers": 1,
    "assets": [
        "example",
        "elasticsearch"
    ],
    "operations": [
        {
            "_op": "elasticsearch_data_generator",
            "size": 5000000
        },
        {
            "_op": "example-op"
        },
        {
            "_op": "elasticsearch_index_selector",
            "index": "terak8s-example-data",
            "type": "events"
        },
        {
            "_op": "elasticsearch_bulk",
            "size": 5000
        }
    ]
}
```

will run and have the following resource names:

```
kubectl -n ts-dev1 get all -l jobId=bf07ef36-c2cb-41be-879c-8c044e86d257
NAME                                                                  READY   STATUS    RESTARTS   AGE
pod/ts-exc-example-data-bad-generator-job-bf07ef36-c2cb-q9zxm         1/1     Running   0          56s
pod/ts-wkr-example-data-bad-generator-job-bf07ef36-c2cb-666ff9fgqwp   1/1     Running   0          56s

NAME                                                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
service/ts-exc-example-data-bad-generator-job-bf07ef36-c2cb   ClusterIP   10.96.106.176   <none>        45680/TCP   56s

NAME                                                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ts-wkr-example-data-bad-generator-job-bf07ef36-c2cb   1/1     1            1           56s

NAME                                                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/ts-wkr-example-data-bad-generator-job-bf07ef36-c2cb-666ff95d99   1         1         1       56s

NAME                                                            COMPLETIONS   DURATION   AGE
job.batch/ts-exc-example-data-bad-generator-job-bf07ef36-c2cb   0/1           56s        56s
```

**Comment by godber** [comment] 2020-01-14 00:12
So, my "fix" for the caps problem is pretty straight forward, I just lowercase the incoming name.  But that's not really sufficient to meet the additional constraints required by kubernetes.  I was already replacing non alpha numerics with `-`.  **But there are additional constraints that aren't as easily glossed over ... namely staring with an alpha and ending with an alphanumeric.**

Do we want to force the `^[alpha].*[alphanum]$` constraint onto Teraslice job names?  Or should I just strip or replace the leading/trailing characters if they are non compliant.  For instance I could do something like this:

```
// and non alpha at the beginning gets replaced with an 'a'
.replace(/[^a-z]/, 'a')
// and non alphanumeric at the end gets replaced with an '0'
.replace(/[a-z0-9$.]/, '0')
```

The way these get used is in labels and names applied to kuberenetes resources.  You can see how they get used as names in the comment above.

**Comment by kstaken** [comment] 2020-01-14 00:19
i don't think we want these restrictions in general on names so continuing to just adjust the labels is probably better.

**Comment by godber** [comment] 2020-01-14 00:33
I'll just go with the simple replacement thing rather than something more flexible to accommodate weird names.  None of this effects uniqueness or identifiability of resources since both the Job name and JobID are used for naming and k8s already appends a unique string onto the end of some things.

It will be possible for the `jobName=` label to clash in cases where I replace "bad" characters.  For instance, the Teraslice job names `//` and `\\` would both result in the same k8s label `jobName=a0`.  I will call out that we don't guarantee uniqueness of `jobName`.  Well, for that matter, we don't enforce uniqueness of Teraslice job names at all, so even with valid characters we could have those collisions.  I guess that's a general thing I should call out in the docs, just in case someone tries to automate something around the `jobName` label.

**Comment by kstaken** [comment] 2020-01-14 00:50
Yeah job names were never intended to be unique, targeting a specific instance of a job is dependent on the ex_id.

**Comment by godber** [comment] 2020-01-23 22:57
released in https://github.com/terascope/teraslice/releases/tag/v0.63.0

**Closed by godber** 2020-01-23 22:57 UTC
Labels: bug, k8s, pkg/teraslice
