### ISSUE TITLE
Production cluster management - Kubernetes

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice#511] opened 2017-08-23 21:51 UTC
The built in clustering is great for getting up and running quickly but for large scale production deployments we want to use a more mature cluster manager to manage resources. The goal is for the clustering interface to be generic and support multiple clustering backends but to start we'll support Kubernetes for the production cluster solution along with our built in native clustering.

This is a tracking ticket for discussion and design. More detail will follow.

### Reminders
- [ ] Don't forget to make sure assets work.
- [ ] How does the master get started?

**Comment by kstaken** [comment] 2017-11-21 22:13
Clustering API has been refactored to enable creation of new clustering backends.

**Comment by godber** [comment] 2018-02-22 21:25
I don't know all of the ways `clusterState` gets used yet but with the native cluster controller (and no jobs running) it looks like this:

```json
{
  "r7c1n7.example.lan": {
    "node_id": "r7c1n7.example.lan",
    "hostname": "10.210.0.104",
    "pid": 1,
    "node_version": "v4.6.1",
    "teraslice_version": "0.28.0",
    "total": 50,
    "state": "connected",
    "available": 48,
    "active": [
      {
        "worker_id": 1,
        "assignment": "cluster_master",
        "pid": 14
      },
      {
        "worker_id": 2,
        "assignment": "assets_service",
        "pid": 20
      }
    ]
  },
  "r7c1n8.example.lan": {
    "node_id": "r7c1n8.example.lan",
    "hostname": "10.210.0.105",
    "pid": 1,
    "node_version": "v4.6.1",
    "teraslice_version": "0.28.0",
    "total": 50,
    "state": "connected",
    "available": 50,
    "active": []
  },
  "r6c1n8.example.lan": {
    "node_id": "r6c1n8.example.lan",
    "hostname": "10.210.0.57",
    "pid": 1,
    "node_version": "v4.6.1",
    "teraslice_version": "0.28.0",
    "total": 50,
    "state": "connected",
    "available": 50,
    "active": []
  }
}
```

It probably makes sense for this to include all k8s nodes, but things like `node_version` don't quite make sense without a persistent node master running.

**Comment by jsnoble** [comment] 2018-02-22 21:30
you may be right that we would need to reconsider what meta data we publish but as for node_version, wont these k8 nodes be running on several different servers that could potentially have different versions of node? would others? Or is this meta data useful at all as it stands?

**Comment by godber** [comment] 2018-02-22 21:36
I don't think I know the answer to those questions yet.  But the fundamental point is that without a persistent node master running, there's nothing to report a `node_version` unless there is a worker running.  I was figuring I could list all the k8s nodes available to run teraslice jobs in cluster state ... but there'd be no source for `node_version`.  Same goes for `pid`, `teraslice_version` and maybe even `state`.  At the very least the meaning of `state` will change ... in the native case, that's whether the node master is connected to the cluster master or something right?  I can redefine `state` = `connected` to mean that the k8s node is available for teraslice workers.  But like I say, it's too early for me to tell.

**Comment by godber** [comment] 2018-03-14 00:28
Targeting kubernetes 1.9.0, these versions:

```
$ minikube version
minikube version: v0.25.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by godber** [comment] 2018-04-03 22:06
## Current status

I've pushed my very preliminary branch here: https://github.com/godber/teraslice/tree/issue-511-add-k8s-clustering

This has the following functionality:

* A simple job without assets can be started (but not stopped), and slices get processed
* Cluster state has things in it, but not the `node_masters`, which breaks the current messaging system, also there are many placeholder values.

```
curl -Ss localhost:5678/cluster/state
{
    "192.168.99.100": {
        "node_id": "192.168.99.100",
        "hostname": "192.168.99.100",
        "pid": 1,
        "node_version": "N/A",
        "teraslice_version": "N/A",
        "total": 42,
        "state": "connected",
        "available": 42,
        "active": [
            {
                "worker_id": "teraslice-slicer-311c9156-c432-4bb4-ab52-a3eae9bc9a10-86c97khlg",
                "assignment": "execution_controller",
                "pid": "teraslice-slicer-311c9156-c432-4bb4-ab52-a3eae9bc9a10-86c97khlg",
                "ex_id": "311c9156-c432-4bb4-ab52-a3eae9bc9a10",
                "job_id": "9facc6f9-59d6-4d3b-83f5-da5c3d9e2448",
                "assets": []
            },
            {
                "worker_id": "teraslice-worker-311c9156-c432-4bb4-ab52-a3eae9bc9a10-7589llvfr",
                "assignment": "worker",
                "pid": "teraslice-worker-311c9156-c432-4bb4-ab52-a3eae9bc9a10-7589llvfr",
                "ex_id": "311c9156-c432-4bb4-ab52-a3eae9bc9a10",
                "job_id": "9facc6f9-59d6-4d3b-83f5-da5c3d9e2448",
                "assets": []
            }
        ]
    }
}
```

* The cluster state above results in `ts-top` output below:

```
######  Nodes  ######

node_id         state      hostname        total  active  pid  teraslice_version  node_version
--------------  ---------  --------------  -----  ------  ---  -----------------  ------------
192.168.99.100  connected  192.168.99.100  42     2       1    N/A                N/A

######  Workers  ######

assignment            job_id                                ex_id                                 node_id         pid
--------------------  ------------------------------------  ------------------------------------  --------------  ---------------------------------------------------------------
execution_controller  9facc6f9-59d6-4d3b-83f5-da5c3d9e2448  311c9156-c432-4bb4-ab52-a3eae9bc9a10  192.168.99.100  teraslice-slicer-311c9156-c432-4bb4-ab52-a3eae9bc9a10-86c97khlg
worker                9facc6f9-59d6-4d3b-83f5-da5c3d9e2448  311c9156-c432-4bb4-ab52-a3eae9bc9a10  192.168.99.100  teraslice-worker-311c9156-c432-4bb4-ab52-a3eae9bc9a10-7589llvfr

######  Slicers  ######

name  job_id  workers_available  workers_active  failed  queued  processed
----  ------  -----------------  --------------  ------  ------  ---------


######  Jobs  ######

job_id                                name           lifecycle   slicers  workers  _created                  _updated
------------------------------------  -------------  ----------  -------  -------  ------------------------  ------------------------
9facc6f9-59d6-4d3b-83f5-da5c3d9e2448  gen-tenk-noop  persistent           1        2018-04-03T21:44:32.874Z  2018-04-03T21:44:32.874Z

######  Execution Contexts  ######

name           lifecycle   slicers  workers  _status  ex_id                                 job_id                                _created                  _updated
-------------  ----------  -------  -------  -------  ------------------------------------  ------------------------------------  ------------------------  ------------------------
gen-tenk-noop  persistent  1        1        running  311c9156-c432-4bb4-ab52-a3eae9bc9a10  9facc6f9-59d6-4d3b-83f5-da5c3d9e2448  2018-04-03T21:44:33.091Z  2018-04-03T21:44:43.650Z

Updated at: Tue Apr 03 2018 14:55:35 GMT-0700 (MST)
```

## Next Steps

After talking with Jared about messaging he points out that all I need is for the `address` to be set to the proper `node_master`.  Like [here](https://github.com/terascope/teraslice/blob/v0.31.0/lib/cluster/services/cluster/backends/native.js#L280-L287)

Looking more I realized that this will be far easier if I run my `cluster_master` inside k8s, because I had been taking the shortcut of running it outside of k8s ... this makes communicating difficult.  So my next step will be to get the `cluster_master` running in k8s and expose the API outside k8s so I can still interact with it.  Once the `cluster_master` is in, then it will be able to directly address the `node_masters`.

- [ ] Don't forget to make sure assets work.

**Comment by godber** [comment] 2018-04-10 22:24
The change [here](https://github.com/godber/teraslice/commit/81d359bad66bf9ba2b4365b7f4a3c2f9121c32c2) get's the teraslice master finally running in k8s.  I'm now able to submit a job and view the cluster state just as I was before.

There was a bunch of local workflow stuff I had to change, locally building dev versions of the teraslice docker container into the k8s, figuring out how to properly address the ES server running on my laptop, figuring out where to find the teraslice master service after exposing it on a nodePort.  Oh and I guess there's the whole `masterDeplyoment.yaml` that I had to create that creates the master pod and service.

Now I am finally going back to trying to get the cluster state working correctly so I can message nodes properly.

**Comment by godber** [comment] 2018-05-23 17:58
I've pushed the nearly working `_scaleDeployment` function.  It would work if it didn't need to authenticate (I ran it through kubectl proxy and it behaves as desired).  Since we've updated to Node 8 I will back up and look at the v5 release of https://github.com/godaddy/kubernetes-client.

**Comment by godber** [comment] 2018-05-23 20:42
I've rebased all of the latest changes in teraslice master, including the node 8 compatibility and package upgrade stuff.  I am abandoning my `issue-511-add-k8s-clustering` (will delete later) and doing my work on this newly rebased branch:

https://github.com/godber/teraslice/tree/issue-511-add-k8s-clustering-node8

**Comment by godber** [comment] 2018-05-24 23:14
I've pushed [a commit](https://github.com/godber/teraslice/commit/2a9ada74d6070f875682591bdaed656068907d57) that swaps out the older kubernetes-client v4 library with the newer v5 library.  The master runs and jobs can be started and stopped.  Now I can go back to scaling the deployment for add/remove/set workers.

**Comment by godber** [comment] 2018-05-31 13:29
I have `_scaleDeplyoement` working for `addWorker` but for some reason it doesn't work with `removeWorker`, still tracking that down.

https://github.com/terascope/teraslice/compare/master...godber:issue-511-add-k8s-clustering-node8

**Comment by godber** [comment] 2018-06-01 18:15
Note: setWorkers or `_workers?total=N` works fine on the branch above, the problem is just with remove.

Ok, I mistakenly assumed that `setWorkers`, `addWorkers`, and `removeWorkers` all received the `execution` as an argument but for some reason `removeWorkers` is passed only the `exId` here:

https://github.com/terascope/teraslice/blob/v0.36.0/lib/cluster/services/execution.js#L106-L118

I don't understand whether that's required for some reason or if it's more of an oversight.

**Comment by jsnoble** [comment] 2018-06-01 20:30
There was no query for the execution context because it is not needed nor used for this command. There was no reason to do another async call. In native clustering all workers/execution_controllers are all tagged by the exId which is used to determine where and what to kill (the exId is provided by the route parameters). Are the kubernetes services not marked by exId?

**Comment by godber** [comment] 2018-06-01 20:47
Yes, they are.  My question was more "why don't these all just take exId?"  But it doesn't matter to me, I'm just working around it.

**Comment by godber** [comment] 2018-06-01 22:28
This commit: https://github.com/terascope/teraslice/commit/117473a75a1ce7c7d4fb508db64233b16887034c resolves the issue with `removeWorker`.

**Comment by jsnoble** [comment] 2018-06-01 22:46
The reason why it does not all take exId is that to remove only the identifier is needed. To create you need the full execution config, which is the reason why the other two actually get it. Set could be a create or a remove so it gets it either way

**Comment by godber** [comment] 2018-06-01 23:03
From an architectural perspective the three functions do roughly the same thing so they'd benefit from having the same interface.  If they all took the `exId` as arguments, then the ones that needed the executions could query for them.  But like I said, it's all good, I made note of it in my code so I am (hopefully) not confused again.

**Comment by kstaken** [comment] 2018-06-01 23:26
@jsnoble, @godber is correct. Any case where you have things so obviously similar it's very important that the APIs be consistent. I know we went over this code fairly closely so I don't know how this slipped past, it's probably my fault, but the reasoning you're providing is not what we want applied when it comes to API design.

**Comment by jsnoble** [comment] 2018-06-02 00:01
I guess im confused at the `From an architectural perspective the three functions do roughly the same thing` comment. To me creation is architectural different from destruction. One needs config, the other just an identifier. Where you trying to make a single function that did all three in kubernetes cluster service? For the code calling these function, the job service only takes a job_id and worker count (which is only what it needs), the execution service only takes a ex_id and worker count  (which is only what it needs) and then gives the cluster service what it needs to do its job. In regards to your statement of `then the ones that needed the executions could query for them` leaves me a little confused as well since that is what the execution service is doing (which is in charge of querying the execution) thus giving the cluster service exactly what it needs to do its job. Its friday, so we can continue this conversation on monday.

**Comment by godber** [comment] 2018-09-18 18:07
The Merged PR above closes this.  We've moved on to addressing individual issues with the `k8s` tag.

**Closed by godber** 2018-09-18 18:07 UTC
Labels: enhancement, priority:high
